### ISSUE TITLE
This on Arch with KDE Plasma 6.1 not working anymore

### ISSUE THREAD

**Issue by voc0der** [Rush/wayland-push-to-talk-fix#14]
Hey, so this was working very well for me before I stupidly upgraded to KDE Plasma 6.1.

The app now runs and looks like it's working the same way (even with Debugging mode) but when I get into discord, it's not sending anything to it. It also worked for mumble before, and not now.

I did get a popup now from KWIN / KDE that didn't happen before asking to `Share input` with the remote window. I opted to allow sharing, and it didn't change anything. I also tried not allowing it later, then allowing it, and remembering. Doesn't seem to impact it.

I uninstalled and rebuilt `wayland-push-to-talk-fix`, no errors anywhere, just doesn't seem to be able to have permission or know what scope to do what it did in 6.1.

I can confirm that the app is indeed capturing out of Window events just fine, its just not sending translated new ones or maybe it is, and other windows can't read it.

Any help is appreciated!

```
/usr/bin/push-to-talk /dev/input/by-id/usb-ROCCAT_ROCCAT_Kone_XP-event-mouse -k BTN_SIDE -n MOUSE8
```

**Comment by voc0der** [comment]
Nevermind, I fixed it by simply using the new feature in KDE  (`Legacy X11 App Support`) > Allow apps to read keystrokes > (`Always` & `Additionally Include Mouse buttons`)

Thank you for your months of service :)

**Comment by Rush** [comment]
Indeed @voc0der, new KDE sunsets a lot of use cases for this repo. I am glad :-)
